### ISSUE TITLE
Final Steps for Migrating Passport App to passport.xyz

### ISSUE THREAD

**Issue by erichfi** [passportxyz/passport#2767]
**Description:**
We need to complete the following steps for the migration of the Passport app to passport.xyz:

1. Update OAuth Callbacks:
  - Review the OAuth Callbacks listed in [this document](https://docs.google.com/document/d/1DTY5Ve5US5ast0fvF1CjpHsMIlUS5wvJjTUsxYwtY0o/edit).
  - Identify missing credentials and create new OAuth apps where necessary.

2. Redirect Domain: (We will not do as part of this work, we'll be running both in parallel for some time before we do the permanent redirect)
  - Redirect from passport.gitcoin.co to passport.xyz.
  - Access to the Gitcoin AWS account is required for this task.

**Tasks:**
- [ ] Ping Gerald to request OAuth access.
- [ ] Confirm OAuth access with either Gerald or Kyle.
- [ ] Reach out to Aditya on the Gitcoin team regarding AWS account access.
- [ ] Update OAuth Callbacks as per the document.
- [ ] Implement domain redirection.
- [ ] Migrate the IAM service to passport.xyz 

Related Issue: [GitHub Issue #2641](https://github.com/passportxyz/passport/issues/2641)

**Comment by Jkd-eth** [comment]
@Kweiss We'll need to get your support to get access to all of the Oauth applications

**Comment by larisa17** [comment]
Status update : 
Github successfully tested on review  with the new app created in the  passport.xyz organization
Google successfully tested  on review with the new app created in the  passport.xyz organization
Outdid: successfully tested on review with redirect URL changed from env variable 
Civic: successfully tested on review  on the new domain 

WIP: linkedin @Larisa 

To Be Done : Discord : new OAuth application is required 

Still to be clarified Coinbase & Idena

**Comment by nutrina** [comment]
I am on to Coinbase
